import "./globals.css";
import { RecoilRoot } from "recoil";
import { useApollo } from "@/lib/apollo/client";
import { ApolloProvider } from "@apollo/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  pageProps,
}: {
  children: React.ReactNode;
  pageProps: any;
}) {
  if (process.env.NEXT_PUBLIC_API_MOCKING === "enabled") {
    require("../lib/mocks");
  }
  const apolloClient = useApollo(pageProps);

  return (
    <ApolloProvider client={apolloClient}>
      <RecoilRoot>
        <html lang="en">
          <body>{children}</body>
        </html>
      </RecoilRoot>
    </ApolloProvider>
  );
}
